name: Python

on: workflow_dispatch

jobs:
  python_38:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Make artifact directory
        run: mkdir -p path/to/artifact
      - name : Save result in Artifact
        run : python -c "import sys; print(sys.version)" >> path/to/artifact/artifact.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/artifact.txt

  python_39:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Make artifact directory
        run: mkdir -p path/to/artifact
      - name : Save result in Artifact
        run : python -c "import sys; print(sys.version)" >> path/to/artifact/artifact.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/artifact.txt
